### ISSUE TITLE
Again endless loop in AbstractNamingFactory.getColumnName

### ISSUE THREAD

**Issue by nonstans** [datanucleus/datanucleus-core#150]
Problem described in #97 occured for an other enhanced class. Maybe it'll be implemented in #30?
Tested using master version.

I attached a unit test demonstrating the issue.
[test.zip](https://github.com/datanucleus/datanucleus-core/files/581228/test.zip)

The endless loop occurs, if I try to get the Extend of the class FeedBackProcessDesc.
In line 184:

> if (embMmds[i].getFullFieldName().equals(mmds.get(mmdNo).getFullFieldName()))

The equals is never true, because embMmds and mmds contain information (for unknown reason) for completely different fields.

Maybe there is something wrong with the annotation of the classes?

**Comment by andyjefferson** [comment]
This has nothing at all to do with the original case (where you had <embedded> and didn't bother specifying _any_ members for the embedded definition). 

Here you seem intent on using annotations to specify embedded info (which is flawed when you want to do nested embedded fields (i.e your case) ... since annotations cannot do that situation), and don't provide embedded info for all members. That is fixed. 

Worth noting also that you specify members in the @Embedded yet don't bother putting the column info in there, so consequently that metadata is of no value at all (the only point of @Embedded with members is to define ORM mapping).
