### ISSUE TITLE
Nesting and referencing

### ISSUE THREAD

**Issue by vreniers** [datanucleus/datanucleus-core#302]
Hi,

In the context of NoSQL document databases; I'm wondering, is it possible to use a combination of nesting embeddable entities and also storing them in separate tables (with joins)?

(Cfr. http://www.datanucleus.org/products/accessplatform_5_2/jpa/mapping.html#embedded_entity)

For example: Computer objects and the Computer part objects are stored within the same table.
However, can you also specify an additional mapping tactic to also store the Computer Parts in their own proprietary table. This implies data duplication ofc, and will the framework then still be able to manage consistency between these duplicates?

I know this is kind of an odd question, but there are scenarios where I believe a combination of denormalization and normalization is ideal.

Kind regards,
Vincent

**Comment by andyjefferson** [comment]
If there is a 1-1 relation to an embedded then it is stored embedded into the owner, always (for any datastore, whether RDBMS or NoSQL). A "join" makes no sense, not that NoSQL do "JOINs" anyway.  Neither JPA nor JDO specs provide for doing that.

The only time an embedded object is stored in a separate place (join table or equivalent) is for RDBMS, MongoDB where there is a 1-N of embeddables. 

Clearly people can contribute new mapping handling if they require it, since all is open source. 

An issue tracker is not the place for asking questions; that is on Gitter or Groups.io, as the docs say. Best follow that.
