### ISSUE TITLE
Add contextual objects to the execution context

### ISSUE THREAD

**Issue by spassignat** [datanucleus/datanucleus-core#368]
hi,

I'm using multitenancy feature with a TenantProvider. The TenantId and TenantReadIds are provided by an "expensive resource" and I wich to cache the values during the life of the EntityManager (ExecutionContext). Actually I maintain a static map in the application but it's getting more and more complex.

It would be great to have a "cache" or contextual map where the application can put values in the ExecutionContext which is cleared when closed.

Exemple:
executionContext.setUserAttribute("key", myObject);
Object o = executionContext.getUserAttribute("key");

thanks

**Comment by andyjefferson** [comment]
Persistence properties already can be set on the PM/EM (ExecutionContext). What benefit does dumping user data into some arbitrary internal class have? 

Yes, JDO allowed such things via
PM.putUserObject, PM.getUserObject
but they are stored on the PM, and I personally never saw the point when its simply store user data in a map for the user, when the user could easily just have their own map.

**Comment by spassignat** [comment]
I haven't really saw the value of that, neither in JDO nor in Object databases, until now with the tenant-provider (which is so so great), which were not cleared by the close method...

From a general aspect, I often have to maintain a context related to persistence. Usually I use a ThreadLocal as most of my applications run on JEE server, or Map. But it's really tedious and a great source of bug, as Threads or Resources used as key, are pooled/reused... So the best would be to have these Maps in the ExecutionContext and maybe also on the PersistenceNucleusContext.


MultiTenancyProvider is intended to be a singleton, set on the PersistenceNucleusContext (EntityManagerFactory).

Actually I need to override the "current" tenant calculated by the MultiTenancyProvider, so to store tenancy information and associate them with the ExecutionContext, I use a Map.

```
public class ECMultitenantProvider implements MultiTenancyProvider {
	static Map<ExecutionContext, MultitenantTenant> TENANTS = new HashMap<>();
[...]
	ExecutionContext.LifecycleListener l = new ExecutionContext.LifecycleListener() {
            public void preClose(ExecutionContext ec) {
                TENANTS.remove(ec);
                ec.getNucleusContext().removeExecutionContextListener(this);
            }
        };
        ec.getNucleusContext().addExecutionContextListener(l);

```

**Comment by spassignat** [comment]
Would this feature acceptable for the product ?

**Comment by chrisco484** [comment]
> From a general aspect, I often have to maintain a context related to persistence. Usually I use a ThreadLocal as most of my applications run on JEE server, or Map. But it's really tedious and a great source of bug, as Threads or Resources used as key, are pooled/reused... So the best would be to have these Maps in the ExecutionContext and maybe also on the PersistenceNucleusContext.
> 

We use a ThreadLocal all the time for this purpose but we've built a framework ([](https://github.com/expojo/expojo)) for it so that it's reliable and reusable across all scenarios.

The trick to avoid issues with thread reuse is to (assuming you're writing a web app) use a Servlet filter to set up the context at the start of a HTTP request and release everything (and perform any required detachment if your Web UI does not do this already) after the HTTP request has been been processed.

It's effectively a "managed" Open Session in View pattern which we have been using without issues for 12 years in many large web applications. The concept is so simple and it works very reliably.

The framework includes its own Servlet filter implementation which establishes it's own ExpojoContext which manages the thread local and establishes and releases a PersistenceProvider/Manager). Just add the Servlet filter to your web app's web.xml.

At any point in your code you simply call the static method ExpojoContext.get() (or use it's alias Ex.get() for brevity) and you instantly have access to the current PersistenceProvider which wraps your JDO or JPA and provides access to any repository or service classes that you register with Expojo.

It doesn't feel right to be loading up these types of application level specific context items within the persistence implementation (DataNucleus) as it should be blissfully unaware of things going up in the application layer.

**Comment by andyjefferson** [comment]
Simply I don't see the point. If this is some feature solely for MultiTenancy, then reword it as that (whereas currently it implies some general dump whatever you want into a persistence context for who knows what reason), with an actual example. Any persistence property that is specifable on the PMF/EMF can, in principle, be specifiable on the PM/EM. Doesn't mean that all properties are currently configured for that, but a MultiTenancyProvider takes in ExecutionContext.

**Comment by spassignat** [comment]
Thanks for these suggestions.

I already tried to manage these information either in ThreadLocal and Map indexed with the ExecutionContext and it's not stable. No idea why after several EntityManager open/close, data are shared between EntityManagers (use data from a previous EntityManager in the same thread or not). For the Map, it's cleared on close with a LifeCycleListener (thanks for this API).

So as I already proxified the EntityManager, I added these contextual persistence data (tenant id) in the proxy and clear them on close. It worked fine with no effort, the reason why I was suggesting.

**Comment by chrisco484** [comment]
I'm using JDO (PersistenceManager) not JPA (EntityManager) but deep down in DataNucleus Core I assume these both are based on the same object.

PersistenceManager/EntityManager are designed to be lightweight, fast to construct objects that you create on demand and that's what Expojo does - creates a new one with each HTTP request then throws it away when the request's response has been completed. Are you holding onto the EntityManager over an extended period of time?

**Comment by chrisco484** [comment]
>  No idea why after several EntityManager open/close, data are shared between EntityManagers (use data from a previous EntityManager in the same thread or not). For the Map, it's cleared on close with a LifeCycleListener (thanks for this API).
> 
> So as I already proxified the EntityManager, I added these contextual persistence data (tenant id) in the proxy and clear them on close. It worked fine with no effort, the reason why I was suggesting.

@spassignat I'm using JDO (PersistenceManager) not JPA (EntityManager) but deep down in DataNucleus Core I assume these both are based on the same class.

PersistenceManager/EntityManager are designed to be lightweight, fast to construct objects that you create on demand and that's what Expojo does - creates a new one with each HTTP request then throws it away when the request's response has been completed. Are you holding onto the EntityManager over an extended period of time?
