### ISSUE TITLE
Mutitenancy tenant an tenant read ids Karnaugh table

### ISSUE THREAD

**Issue by spassignat** [datanucleus/datanucleus-core#408]
The behavior of tenant and tenant-read-ids is the following on some read operation (most of them except fetching hollow object at least):

| tenant / read-ids |null or 0    | 1      | many   |
---------------|:------:|:------:|:------:|
| null         | A: skip | B: tenant | C: read-ids|
| not null     | D: tenant | E: tenant | F: tenant |

When using a Provider (I mean a programmatic approach of tenant), the case B is complex unexpected. (if you have only one element in the read-ids whatever the tenant value you use the tenant value). It's even more unexpected when tenant the tenant value is null.

I think it would be easier to have, one of these solution:

| tenant / read-ids |null or 0    | 1      | many   |
---------------|:------:|:------:|:------:|
| null         | A: skip | B: read-ids | C: read-ids|
| not null     | D: tenant | E: tenant | F: tenant |

| tenant / read-ids |null or 0    | 1      | many   |
---------------|:------:|:------:|:------:|
| null         | A: skip | B: read-ids | C: read-ids|
| not null     | D: tenant+read-ids | E: tenant+read-ids | F: tenant+read-ids |

Can this be an evolution ?

**Comment by andyjefferson** [comment]
Current code (RDBMS) will do the following for reads : 
1. use tenantReadIds when specified (non null)
2. use tenantId otherwise. 

Non-RDBMS don't support tenantReadIds (still). 

This change makes little difference to users. If specifying tenantReadIds the only real point is when specifying tenantId PLUS some other ids (i.e number of values > 1).
