### ISSUE TITLE
Upgrade logging to use Log4j 2.x

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-core#48]
If possible allow support for Log4j v1 and v2 and so it chooses v2 if present in the CLASSPATH, else v1, else j.u.l

This has Log4j2Logger in datanucleus-core, but with the default still Log4j v1.

Remaining work to make Log4j v2 as default
1. PluginParserTest has some use of Appender to detect messages raised. Needs changing to use v2  **DONE**
2. Add log4j v2 config files (to replace log4j.properties)
3. Update Maven/Eclipse to allow Log4j v2 config file.  **Maven DONE**

**Comment by chrisco484** [comment]
Does that mean that currently DN 4.x is using Log4j v1.2.x?

I have just moved an app from Log4j 1.2.x to Log4j 2.x and the DN runtime enhancement agent gives class not found exceptions on all the persistent classes that live in jar libraries that the application uses.

When I switch back to Log4j 1.2.x DN is happy again.

If DN requires Log4j v1.2.x then that should be fine - the app is written to the Log4j 1.2.x API but then we use the Log4J 1.2.x -> Log4j 2.x bridge so that should mean DN should also be able to bind to the Lo4j 2 core even though it's using Log4j 1.2.x API.

**Comment by andyjefferson** [comment]
It uses what it finds. If log4j v1 is present it uses that, otherwise v2 if found, otherwise JRE logging.

DN tests run perfectly fine with Log4j v2 (no we don't use runtime enhancement). Any exceptions you get are certainly not due to logging, since they are thrown before the log is involved! This is simply another issue where people have said "I want this, I want this" and then when the time comes to actually do things it all goes quiet. aka "the open source world".

**Comment by chrisco484** [comment]
Personally, I would have been happy if the Java world just stuck with the single logging solution (log4j X) rather than inventing an abstraction layer to cater for a range of different logging solutions that all do pretty much the same thing.
The situation wasn't helped when even the author of the defacto standard logging solution 'log4j' decides to write a different one 'logback' :]

**Comment by chrisco484** [comment]
I've fixed the above problem by being specific about which packages the enhancement agent should attempt to enhance at runtime by specifying the packages after the api=JDO in the -D option.
For some reason it needed no package filtering when using Junit 1.x but with Junit 2.x it starts up in a very strange way without it.
I could have just been lucky before ;)

**Comment by andyjefferson** [comment]
DN tests now moved across to Log4j2. If no Log4j v1 is found in classpath and Log4j2 is then that is used. Nothing more to do in this issue. User can always put Log4j2 log config in valid default locations in classpath to get it read
